top_stories_limit: 50
comments_limit: 10
api_concurrency: 5
areas_of_interest:
  - Security vulnerabilities, hacking
  - Machine Learning
  - Programming languages
  - Electronics
  - 3D printing
  - Software design & architecture
  - Better software development practices
  - How to work faster and more efficiently
