name: Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x run.sh

      - name: Run script
        run: ./run.sh
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push index.html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Latest run $(TZ='Pacific/Auckland' date +'%Y-%m-%d %H:%M')"
          file_pattern: index.html