name: Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x run.sh

      - name: Run script
        run: ./run.sh
